server:
  port: 9090

spring:
  application:
    name: admin-server
  thymeleaf:
    check-template-location: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: admin-server
    description: Spring Boot Admin server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
