server:
  port: 8083

spring:
  application:
    name: payment-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,env,threaddump,heapdump
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: payment-service
    description: Payment processing service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
