#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<SQL
CREATE DATABASE ${PLATFORM_DB_NAME};
CREATE ROLE ${DB_ADMIN_USERNAME} LOGIN PASSWORD '${DB_ADMIN_PASSWORD}';
CREATE ROLE ${USER_DB_USERNAME} LOGIN PASSWORD '${USER_DB_PASSWORD}';
CREATE ROLE ${ORDER_DB_USERNAME} LOGIN PASSWORD '${ORDER_DB_PASSWORD}';
CREATE ROLE ${PAYMENT_DB_USERNAME} LOGIN PASSWORD '${PAYMENT_DB_PASSWORD}';
GRANT CONNECT ON DATABASE ${PLATFORM_DB_NAME} TO ${DB_ADMIN_USERNAME};
GRANT CONNECT ON DATABASE ${PLATFORM_DB_NAME} TO ${USER_DB_USERNAME};
GRANT CONNECT ON DATABASE ${PLATFORM_DB_NAME} TO ${ORDER_DB_USERNAME};
GRANT CONNECT ON DATABASE ${PLATFORM_DB_NAME} TO ${PAYMENT_DB_USERNAME};
SQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$PLATFORM_DB_NAME" <<SQL
GRANT ALL PRIVILEGES ON DATABASE ${PLATFORM_DB_NAME} TO ${DB_ADMIN_USERNAME};
GRANT USAGE, CREATE ON SCHEMA public TO ${DB_ADMIN_USERNAME};

CREATE SCHEMA admin_server AUTHORIZATION ${DB_ADMIN_USERNAME};

CREATE SCHEMA user_service AUTHORIZATION ${DB_ADMIN_USERNAME};
CREATE SCHEMA order_service AUTHORIZATION ${DB_ADMIN_USERNAME};
CREATE SCHEMA payment_service AUTHORIZATION ${DB_ADMIN_USERNAME};

GRANT USAGE ON SCHEMA user_service TO ${USER_DB_USERNAME};
GRANT USAGE ON SCHEMA order_service TO ${ORDER_DB_USERNAME};
GRANT USAGE ON SCHEMA payment_service TO ${PAYMENT_DB_USERNAME};

ALTER DEFAULT PRIVILEGES FOR ROLE ${DB_ADMIN_USERNAME} IN SCHEMA user_service
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${USER_DB_USERNAME};
ALTER DEFAULT PRIVILEGES FOR ROLE ${DB_ADMIN_USERNAME} IN SCHEMA order_service
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${ORDER_DB_USERNAME};
ALTER DEFAULT PRIVILEGES FOR ROLE ${DB_ADMIN_USERNAME} IN SCHEMA payment_service
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${PAYMENT_DB_USERNAME};

ALTER DEFAULT PRIVILEGES FOR ROLE ${DB_ADMIN_USERNAME} IN SCHEMA user_service
GRANT USAGE, SELECT ON SEQUENCES TO ${USER_DB_USERNAME};
ALTER DEFAULT PRIVILEGES FOR ROLE ${DB_ADMIN_USERNAME} IN SCHEMA order_service
GRANT USAGE, SELECT ON SEQUENCES TO ${ORDER_DB_USERNAME};
ALTER DEFAULT PRIVILEGES FOR ROLE ${DB_ADMIN_USERNAME} IN SCHEMA payment_service
GRANT USAGE, SELECT ON SEQUENCES TO ${PAYMENT_DB_USERNAME};
SQL
