apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      manageAlerts: true
      allowAsRecordingRulesTarget: true
      prometheusType: Prometheus
      timeInterval: 15s
    isDefault: true
    editable: true
